name: build

on:
  push:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: 386
      -
        name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - 
        name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip \
          dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc \
          qemu-utils kpartx jq
      - 
        name: Building fusee-framboise hekate
        run: echo "HEKATE_LATEST_URL=`curl -sL https://api.github.com/repos/CTCaer/hekate/releases/latest | jq -r '.assets[].browser_download_url' | grep hekate_ctcaer`" >> $GITHUB_ENV
        run: echo "HEKATE_LATEST_TAG=`curl -sL https://api.github.com/repos/CTCaer/hekate/releases/latest | jq -r '.tag_name' | sed s/v/\/`" >> $GITHUB_ENV
        run: sudo IMG_NAME=fusee-framboise-hekate DEPLOY_ZIP=0 ./build.sh
      - 
        run: ls -la deploy